services:
  - type: web
    name: kizuno-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false
      - key: SMTP_EMAIL
        value: kizuno.ai.in@gmail.com
      - key: SMTP_APP_PASSWORD
        value: vbgpxofsjvkkjejw
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "465"
      - key: ADMIN_PIN
        value: "9812"

